stations_dict = {
    1: {
        "Name": "BMW OF DARIEN",
        "location": "138-142 Ledge Rd",
        "City": "Darien",
        "capacity": 15,
        "status": True,
    },
    2: {
        "Name": "Dunkin' - Tesla Supercharger",
        "location": "893 E Main St",
        "City": "Meriden",
        "capacity": 22,
        "status": False,
    },
    3: {
        "Name": "Town of Beacon Falls - Commuter Lot",
        "location": "105 N Main St",
        "City": "Beacon Falls",
        "capacity": 7,
        "status": True,
    },
    4: {
        "Name": "OLD SAYBROOK VW",
        "location": "319 Middlesex Turnpike",
        "City": "Old Saybrook",
        "capacity": 19,
        "status": False,
    },
    5: {
        "Name": "Fairfield Rail Station",
        "location": "80 Mill Plain Rd",
        "City": "Fairfield",
        "capacity": 12,
        "status": True,
    },
    6: {
        "Name": "FOUNDRY66",
        "location": "50 Franklin St",
        "City": "Norwich",
        "capacity": 8,
        "status": False,
    },
    7: {
        "Name": "Corbins Corner Shopping Center - Tesla Supercharger",
        "location": "1445 New Britain Ave.",
        "City": "West Hartford",
        "capacity": 28,
        "status": True,
    },
    8: {
        "Name": "GLASTONBURYEV",
        "location": "2327-2333 Main St",
        "City": "Glastonbury",
        "capacity": 14,
        "status": True,
    },
    9: {
        "Name": "Whole Foods Market",
        "location": "150 Ledge Rd",
        "City": "Darien",
        "capacity": 20,
        "status": False,
    },
    10: {
        "Name": "Mystic Marriott Hotel and Spa",
        "location": "625 North Rd",
        "City": "Groton",
        "capacity": 5,
        "status": True,
    },
    11: {
        "Name": "Brass Mill Center - Shoppers World",
        "location": "495 Union St",
        "City": "Waterbury",
        "capacity": 17,
        "status": False,
    },
    12: {
        "Name": "University of Connecticut Health - Center Garage",
        "location": "263 Farmington Ave",
        "City": "Farmington",
        "capacity": 25,
        "status": True,
    },
    13: {
        "Name": "D'Addario Nissan",
        "location": "329 Bridgeport Ave",
        "City": "Shelton",
        "capacity": 9,
        "status": False,
    },
    14: {
        "Name": "CT RAIL",
        "location": "198 N Cherry St",
        "City": "Wallingford",
        "capacity": 13,
        "status": True,
    },
    15: {
        "Name": "Hampton Inn & Suites Rocky Hill - Hartford South - Tesla Destination",
        "location": "685 Cromwell Ave",
        "City": "Rocky Hill",
        "capacity": 18,
        "status": False,
    },
    16: {
        "Name": "Goodwives Shopping Center",
        "location": "25 Old Kings Hwy",
        "City": "Darien",
        "capacity": 6,
        "status": True,
    },
    17: {
        "Name": "City of New Haven - Union Station Garage",
        "location": "50 Union Ave",
        "City": "New Haven",
        "capacity": 24,
        "status": False,
    },
    18: {
        "Name": "Easton Public Library",
        "location": "691 Morehouse Rd",
        "City": "Easton",
        "capacity": 11,
        "status": True,
    },
    19: {
        "Name": "The Plaza at Buckland Hills - Tesla Supercharger",
        "location": "1470 Pleasant Valley Road",
        "City": "Manchester",
        "capacity": 30,
        "status": False,
    },
    20: {
        "Name": "Greenlots - 92367",
        "location": "204 Stillman Hill Rd",
        "City": "Colebrook",
        "capacity": 4,
        "status": True,
    },
    21: {
        "Name": "Mystic Diner Restaurant - Tesla Destination",
        "location": "253 Greenmanville Ave",
        "City": "Mystic",
        "capacity": 16,
        "status": False,
    },
    22: {
        "Name": "Connecticut Airport Authority - Bradley Airport",
        "location": "Cell Phone Lot",
        "City": "Windsor Locks",
        "capacity": 27,
        "status": True,
    },
    23: {
        "Name": "University of Connecticut - Motor Pool",
        "location": "9 Discovery Dr",
        "City": "Storrs",
        "capacity": 3,
        "status": False,
    },
    24: {
        "Name": "Hammonasset Beach State Park - South",
        "location": "1288 Boston Post Rd",
        "City": "Madison",
        "capacity": 21,
        "status": True,
    },
    25: {
        "Name": "Schaller Mitsubishi",
        "location": "25 Veterans Dr",
        "City": "New Britain",
        "capacity": 10,
        "status": False,
    },
    26: {
        "Name": "Mansfield Public Library",
        "location": "54 Warrenville Rd",
        "City": "Mansfield",
        "capacity": 2,
        "status": True,
    },
    27: {
        "Name": "WESTLODGE",
        "location": "811 Burr Mountain Rd",
        "City": "Torrington",
        "capacity": 23,
        "status": False,
    },
    28: {
        "Name": "TOWNHALL",
        "location": "100 Bentley Dr",
        "City": "Harwinton",
        "capacity": 1,
        "status": True,
    },
    29: {
        "Name": "University of Connecticut - Avery Point",
        "location": "1084 Shennecossett Rd",
        "City": "Groton",
        "capacity": 29,
        "status": False,
    },
    30: {
        "Name": "Middletown School District - Lawrence Elementary School",
        "location": "Kaplan Dr",
        "City": "Middletown",
        "capacity": 14,
        "status": True,
    },
    31: {
        "Name": "Fairfield Mitsubishi",
        "location": "421 Tunxis Hill Rd",
        "City": "Fairfield",
        "capacity": 8,
        "status": False,
    },
    32: {
        "Name": "Gates Nissan",
        "location": "143 Boston Post Rd",
        "City": "North Windham",
        "capacity": 26,
        "status": True,
    },
    33: {
        "Name": "Water's Edge Resort and Spa - Tesla Destination",
        "location": "1525 Boston Post Rd",
        "City": "Westbrook",
        "capacity": 17,
        "status": False,
    },
    34: {
        "Name": "North Haven PaviIion",
        "location": "100 Universal Dr",
        "City": "North Haven",
        "capacity": 12,
        "status": True,
    },
    35: {
        "Name": "UNION STATION",
        "location": "Union Ave and Union Station",
        "City": "New Haven",
        "capacity": 28,
        "status": False,
    },
    36: {
        "Name": "Torrington Town Hall",
        "location": "140 Main St",
        "City": "Torrington",
        "capacity": 5,
        "status": True,
    },
    37: {
        "Name": "Crowley Nissan",
        "location": "1451 Farmington Ave",
        "City": "Bristol",
        "capacity": 19,
        "status": False,
    },
    38: {
        "Name": "Parthenon Diner Restaurant - Tesla Destination",
        "location": "374 E Main St",
        "City": "Branford",
        "capacity": 7,
        "status": True,
    },
    39: {
        "Name": "Town of Mansfield - Community Center",
        "location": "10 S Eagleville Rd",
        "City": "Mansfield",
        "capacity": 16,
        "status": False,
    },
    40: {
        "Name": "Manchester City Nissan",
        "location": "30 Tolland Turnpike",
        "City": "Manchester",
        "capacity": 11,
        "status": True,
    },
    41: {
        "Name": "City of Meriden - City Hall",
        "location": "142 E Main St",
        "City": "Meriden",
        "capacity": 22,
        "status": False,
    },
    42: {
        "Name": "City of New Haven - Sherman Tyler Lot",
        "location": "60 N Frontage Rd",
        "City": "New Haven",
        "capacity": 3,
        "status": True,
    },
    43: {
        "Name": "City of Meriden - Meriden Public Library",
        "location": "105 Miller St",
        "City": "Meriden",
        "capacity": 27,
        "status": False,
    },
    44: {
        "Name": "Blogoslawski Parking Garage",
        "location": "10 Franklin Square",
        "City": "New Britain",
        "capacity": 9,
        "status": True,
    },
    45: {
        "Name": "Comfort Inn Guilford - Tesla Destination",
        "location": "300 Boston Post Rd",
        "City": "Guilford",
        "capacity": 20,
        "status": False,
    },
    46: {
        "Name": "Brass Mill Center - Entrance 5",
        "location": "495 Union St",
        "City": "Waterbury",
        "capacity": 6,
        "status": True,
    },
    47: {
        "Name": "Town of Simsbury - Town Hall",
        "location": "933 Hopmeadow St",
        "City": "Simsbury",
        "capacity": 24,
        "status": False,
    },
    48: {
        "Name": "Connecticut Legislative Parking Garage",
        "location": "240 Capitol Ave",
        "City": "Hartford",
        "capacity": 13,
        "status": True,
    },
    49: {
        "Name": "Middletown School District - Moody School",
        "location": "300 Country Club Rd",
        "City": "Middletown",
        "capacity": 18,
        "status": False,
    },
}
